my:
  key: 314159265358979323846
  token-timeout: 86400000  # 24h
spring:
  application:
    name: carbon-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/challenger-cup?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 31415926
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
  servlet:
    context-path: /api
logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.web: DEBUG
    com.yuki.carbonserver.mapper: DEBUG
    com.yuki.carbonserver.utils: DEBUG
  file:
    name: ./logs/app.log
pagehelper:
  helper-dialect: mysql  # ?????
  reasonable: true       # ???????
  support-methods-arguments: true
  return-page-info: always
